name: Test
on:
  push: {}
  pull_request: {}
jobs:
  run:
    runs-on: macOS-latest
    name: Swift test
    steps:
    - uses: actions/checkout@master
    - name: Install tooling
      run: |
        sudo xcode-select -s /Applications/Xcode_11.5.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Resolve
      run: swift package resolve
    - name: Build
      run: swift build
    - name: Test
      run: set -o pipefail && swift test 2>&1 | xcpretty
